closeAllConnections()
rm(list = ls(all = TRUE))


library(stringr)
source("C://users/John/Google Drive/R libraries/Libraries.R")
source(str_c("C://users/John/Google Drive/Mind Games/",
             "Transportation/Making a demand flow matrix/functions_randomchanges.R"))
options(expressions = 500000)

# The demand matrix is the stochastic matrix that will be generated by a demand function
size = "Ethan Allen"
demand_matrix = get_dm(size)
station_entries = get_entries(size)
terminal_difference = .25 # This is the maximum allowable summed squared error
percentage_change = 100 # When adjusting an individual error, this is the 
#percentage of the error to adjust
probability_of_better = 1.01 # Continue until the probability of finding a better 
#matrix is less than this
repeats = 10 # Number of times in a row to change one particular i/j combination.  
    #Increase this to approach the terminal condition faster (I think).
repeats_plusorminus = repeats - 1 # Repeats will randomly add or subtract up to 
#this amount from itself

# Multiplies the stochastic demand matrix by the station entries
demand_flow = make_df(demand_matrix, station_entries)
rownames(demand_flow) = colnames(demand_flow)

# Find station entries
new_df = adjust_df_ratio(demand_flow, terminal_difference, percentage_change, 
                         probability_of_better, repeats)

load_profile = create_load_profile(new_df)

finish(size, new_df, load_profile)
